### ISSUE TITLE
Grad-CAM for regression DL model?

### ISSUE THREAD

**Issue by pirocv** [anhquan0412/animation-classification#1]
Hello. 
Thank you for sharing your work.
I'm studying deep learning in fastai course and trying to visualize my DL model.
I found your work about Grad-CAM and guided Grad-CAM visualization in the fastai forum's post and it is really helpful to me.

I've created a DL model to predict age from a picture using transfer learning and now I'd like to visualize this model. I've tried your code on my model.
It didn't work and I got an error like the one below.
I suspect that it may be because my model is a regression model.
Can you tell me how to make your code work with the regression model?

My model is resnet based model and was trained using transfer learning as taught in fastai course.

```
      1 test_img = path/'437.png'
      2 img = open_image(test_img);
----> 3 gcam = GradCam.from_one_img(learn,img)
      4 gcam.plot()

/gradcam.py in from_one_img(cls, learn, x_img, label1, label2)
     51         probs = probs.numpy()
     52 
---> 53         label1_idx = learn.data.classes.index(label1)
     54         hmap1, xb_grad1 = get_grad_heatmap(learn, xb, label1_idx, size=xb_img.shape[-1])
     55         prob1 = probs[label1_idx]

/lib/python3.7/site-packages/fastai/basic_data.py in __getattr__(self, k)
    120         return cls(*dls, path=path, device=device, dl_tfms=dl_tfms, collate_fn=collate_fn, no_check=no_check)
    121 
--> 122     def __getattr__(self,k:int)->Any: return getattr(self.train_dl, k)
    123     def __setstate__(self,data:Any): self.__dict__.update(data)
    124 

/lib/python3.7/site-packages/fastai/basic_data.py in __getattr__(self, k)
     36 
     37     def __len__(self)->int: return len(self.dl)
---> 38     def __getattr__(self,k:str)->Any: return getattr(self.dl, k)
     39     def __setstate__(self,data:Any): self.__dict__.update(data)
     40 

/lib/python3.7/site-packages/fastai/basic_data.py in DataLoader___getattr__(dl, k)
     18 torch.utils.data.DataLoader.__init__ = intercept_args
     19 
---> 20 def DataLoader___getattr__(dl, k:str)->Any: return getattr(dl.dataset, k)
     21 DataLoader.__getattr__ = DataLoader___getattr__
     22 

/lib/python3.7/site-packages/fastai/data_block.py in __getattr__(self, k)
    641         res = getattr(y, k, None)
    642         if res is not None: return res
--> 643         raise AttributeError(k)
    644 
    645     def __setstate__(self,data:Any): self.__dict__.update(data)

AttributeError: classes
```

**Comment by anhquan0412** [comment]
Hi!
Sorry for the delay! And thanks for the interest in my code!
Yes, you are right that my current gradcam code is not suitable for regression model, and the original gradcam paper doesn't mention anything about regression model. I think it is still possible to use gradcam in this case since the idea of GradCam is to calculate gradient with respect to a target layer; the gradient can come from classification or regression output, but due to lack of google results for the term 'gradcam on regression model', I don't think it's gonna work as well as the classification one.
